# Generated by Django 5.0.6 on 2025-05-29 09:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.UUIDField(db_column='fee_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('mandatory', 'Mandatory'), ('voluntary', 'Voluntary')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fees',
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.UUIDField(db_column='household_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('household_number', models.TextField()),
                ('household_size', models.IntegerField()),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'households',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(db_column='user_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('password_hash', models.TextField()),
                ('role', models.CharField(choices=[('chu_ho', 'Head of Household'), ('thu_ky', 'Accountant'), ('to_trương', 'Group Leader'), ('to_pho', 'Vice Group Leader')], max_length=20)),
                ('fullname', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.UUIDField(db_column='member_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('other_name', models.TextField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('place_of_birth', models.TextField(blank=True, null=True)),
                ('native_place', models.TextField(blank=True, null=True)),
                ('ethnic_group', models.TextField(blank=True, null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('place_of_work', models.TextField(blank=True, null=True)),
                ('cccd', models.TextField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('issued_by', models.TextField(blank=True, null=True)),
                ('relationship', models.TextField()),
                ('is_temporary', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('joined_at', models.DateField()),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.household')),
            ],
            options={
                'db_table': 'household_members',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(db_column='payment_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paid_at', models.DateTimeField()),
                ('method', models.CharField(choices=[('qr_code', 'QR'), ('cash', 'Cash'), ('card', 'Card')], max_length=20)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=20)),
                ('fee', models.ForeignKey(db_column='fee_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.fee')),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.household')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='ResidencyRequest',
            fields=[
                ('id', models.UUIDField(db_column='request_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=30)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('destination', models.TextField()),
                ('origin', models.TextField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='residency_requests', to='core.user')),
            ],
            options={
                'db_table': 'residency_requests',
            },
        ),
        migrations.CreateModel(
            name='HouseholdChange',
            fields=[
                ('id', models.UUIDField(db_column='change_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('add_member', 'Add Member'), ('remove_member', 'Remove Member'), ('update_info', 'Update Info'), ('change_head', 'Change Household Head')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('household', models.ForeignKey(db_column='household_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='core.household')),
                ('approved_by', models.ForeignKey(db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_approved', to='core.user')),
                ('requested_by', models.ForeignKey(db_column='requested_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_requested', to='core.user')),
            ],
            options={
                'db_table': 'household_changes',
            },
        ),
        migrations.AddField(
            model_name='household',
            name='head',
            field=models.ForeignKey(db_column='head_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to='core.user'),
        ),
        migrations.AddField(
            model_name='fee',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='core.user'),
        ),
    ]
