# Generated by Django 5.0.6 on 2025-05-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='households',
            field=models.ManyToManyField(blank=True, db_table='fee_households', related_name='private_fees', to='core.household'),
        ),
        migrations.AddField(
            model_name='fee',
            name='is_common',
            field=models.BooleanField(db_column='is_common', default=True),
        ),
    ]
