# Generated by Django 5.0.6 on 2025-05-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fee',
            table='fees',
        ),
        migrations.AlterModelTable(
            name='household',
            table='households',
        ),
        migrations.AlterModelTable(
            name='householdchange',
            table='household_changes',
        ),
        migrations.AlterModelTable(
            name='householdmember',
            table='household_members',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
        migrations.AlterModelTable(
            name='residencyrequest',
            table='residency_requests',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
