# Generated by Django 5.0.6 on 2025-05-26 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fee_table_alter_household_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='householdchange',
            old_name='household',
            new_name='household_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='fee',
            new_name='fee_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='household',
            new_name='household_id',
        ),
        migrations.RenameField(
            model_name='residencyrequest',
            old_name='user',
            new_name='user_id',
        ),
    ]
