# Generated by Django 5.0.6 on 2025-05-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_household_householdchange_household_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='householdchange',
            old_name='household_id',
            new_name='household',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='fee_id',
            new_name='fee',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='household_id',
            new_name='household',
        ),
        migrations.RenameField(
            model_name='residencyrequest',
            old_name='user_id',
            new_name='user',
        ),
    ]
