# Generated by Django 5.0.6 on 2025-05-26 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_household_id_householdchange_household_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee_id',
            field=models.UUIDField(db_column='fee_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='fee_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='household',
            name='household_id',
            field=models.UUIDField(db_column='household_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='household',
            old_name='household_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='householdchange',
            name='change_id',
            field=models.UUIDField(db_column='change_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='householdchange',
            old_name='change_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='member_id',
            field=models.UUIDField(db_column='member_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='householdmember',
            old_name='member_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.UUIDField(db_column='payment_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='residencyrequest',
            name='request_id',
            field=models.UUIDField(db_column='request_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='residencyrequest',
            old_name='request_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(db_column='user_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='fee',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='core.user'),
        ),
        migrations.AlterField(
            model_name='household',
            name='head',
            field=models.ForeignKey(db_column='head', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to='core.user'),
        ),
        migrations.AlterField(
            model_name='householdchange',
            name='approved_by',
            field=models.ForeignKey(db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_approved', to='core.user'),
        ),
        migrations.AlterField(
            model_name='householdchange',
            name='household',
            field=models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='core.household'),
        ),
        migrations.AlterField(
            model_name='householdchange',
            name='requested_by',
            field=models.ForeignKey(db_column='requested_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_requested', to='core.user'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='household',
            field=models.ForeignKey(db_column='household', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.household'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fee',
            field=models.ForeignKey(db_column='fee_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.fee'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='household',
            field=models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.household'),
        ),
        migrations.AlterField(
            model_name='residencyrequest',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='residency_requests', to='core.user'),
        ),
    ]
