# Generated by Django 5.0.6 on 2025-05-26 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_fee_fee_id_rename_fee_id_fee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='head',
            field=models.ForeignKey(db_column='head_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to='core.user'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='household',
            field=models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.household'),
        ),
    ]
